### ISSUE TITLE
Question about evaluating Llama-3-8B-Instruct on LongBench

### ISSUE THREAD

**Issue by jameslahm** [Zefan-Cai/PyramidKV#12]
Thanks for your great work! I try to run Llama-3-8B-Instruct on LongBench according to the README. My environment is
```bash
transformers==4.41.0
flash-attn==2.4.0.post1
```
I evaluate LLama-3-8B-Instruct using PyramidKV as follows
```bash
export CUDA_VISIBLE_DEVICES=0

method="PyramidKV" # Support PyramidKV, SnapKV, H2O, StreamingLLM
max_capacity_prompts=128 # 128,2048 in paper
attn_implementation="flash_attention_2" # Support "flash_attention_2", "sdpa", "eager".
model_path="Meta-Llama-3-8B-Instruct"
save_dir="results_long_bench" # path to result save_dir

python3 run_longbench.py \
    --method ${method} \
    --model_path ${model_path} \
    --max_capacity_prompts ${max_capacity_prompts} \
    --attn_implementation ${attn_implementation} \
    --save_dir ${save_dir} \
    --use_cache True
```
And then I run `scripts/scripts_longBench/metrics.sh` to obtain the results. However, the score on `narrativeqa` is `2.92`, as follows
```
dataset narrativeqa method PyramidKV scores {'narrativeqa': 2.92}
```
To obtain the Llama-3-8B-Instruct model, I first download the checkpoint according to https://llama.meta.com/llama-downloads/. And I then use the script https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/convert_llama_weights_to_hf.py to obtain the weights in the format of transformers. I am not very sure if I miss something. Could you give me some guidance about this? Thanks very much!

**Comment by Zefan-Cai** [comment]
Would you mind using the hf model of meta-llama/Meta-Llama-3-8B-Instruct from hugging face website instead of manually transferring a checkpoint to hf checkpoint?

**Comment by jameslahm** [comment]
@Zefan-Cai Thanks for your reply! I switch to the hf model of meta-llama/Meta-Llama-3-8B-Instruct and the results become normal. But I found the results are slightly different from those in the paper. For example, using `max_capacity_prompts=128`, the score on `multifieldqa_en` is 33.07 and 41.88 with `method="PyramidKV"` and `method="FullKV"`, respectively. The corresponding results are 33.79 and 41.12 in the paper. Are these differences expected due to the different hardware? I use the RTX 4090 device. Thanks!

**Comment by Zefan-Cai** [comment]
These differences may be expected due to the device reason. We use Nvidia A100 for the experiments.

**Comment by jameslahm** [comment]
Thanks for your reply!

**Comment by Dominic789654** [comment]
> Would you mind using the hf model of meta-llama/Meta-Llama-3-8B-Instruct from hugging face website instead of manually transferring a checkpoint to hf checkpoint?

I'm encountering the same issue. Why would this difference lead to varying results?

**Comment by Zefan-Cai** [comment]
> > Would you mind using the hf model of meta-llama/Meta-Llama-3-8B-Instruct from hugging face website instead of manually transferring a checkpoint to hf checkpoint?
> 
> 
> 
> I using the model download from the hugging face website. I'm encountering the same issue. Why would this difference lead to varying results?

I am also unsure about this. This is probably because the transfer code is not correct. Anyway, just use the checkpoint from huggingface website and you can avoid this issue.

**Comment by icoderzqliu** [comment]
> > > Would you mind using the hf model of meta-llama/Meta-Llama-3-8B-Instruct from hugging face website instead of manually transferring a checkpoint to hf checkpoint?
> > 
> > 
> > I using the model download from the hugging face website. I'm encountering the same issue. Why would this difference lead to varying results?
> 
> I am also unsure about this. This is probably because the transfer code is not correct. Anyway, just use the checkpoint from huggingface website and you can avoid this issue.

Hello, I just use the checkpoint from huggingface website and still have the same issue. The results is significantly lower compared to the results in the paper. It seems that the model did not stop correctly, leading to lower results. Could this be due to incorrect template configuration? I don‘t see any code related to chat template for llama-3-8b-instruct in the codebase. I am unsure whether the final inference results you obtained had the same issues with mine, or if you had implemented any special handling for this. I look forward to your response. Thank you very much!

**Comment by Zefan-Cai** [comment]
> > > > Would you mind using the hf model of meta-llama/Meta-Llama-3-8B-Instruct from hugging face website instead of manually transferring a checkpoint to hf checkpoint?
> > > 
> > > 
> > > I using the model download from the hugging face website. I'm encountering the same issue. Why would this difference lead to varying results?
> > 
> > 
> > I am also unsure about this. This is probably because the transfer code is not correct. Anyway, just use the checkpoint from huggingface website and you can avoid this issue.
> 
> Hello, I just use the checkpoint from huggingface website and still have the same issue. The results is significantly lower compared to the results in the paper. It seems that the model did not stop correctly, leading to lower results. Could this be due to incorrect template configuration? I don‘t see any code related to chat template for llama-3-8b-instruct in the codebase. I am unsure whether the final inference results you obtained had the same issues with mine, or if you had implemented any special handling for this. I look forward to your response. Thank you very much!

Implementation for  llama-3-8b-instruct without chat template is acceptable and can lead to reasonable results. Our reported results is based on the input format at our current codebase. If the issue is that the model does not stop,consider adding '\n' and eos_token at the below line.

https://github.com/Zefan-Cai/PyramidKV/blob/73c08b1dc1104b2d614c0670478d297a7a4df8c1/run_longbench.py#L253
