### ISSUE TITLE
Strange Results of Mistral

### ISSUE THREAD

**Issue by yuhuixu1993** [Zefan-Cai/PyramidKV#13]
Thanks for sharing the code. I am a little bit confused about the results of mistral on LongBench especially the task Multi-news which is extremely lower than what is reported in SnapKV. Any reasons?

**Comment by Zefan-Cai** [comment]
Thank you so much for pointing out!

The reason that the results of mistral on LongBench - Multi-news is especially low is: We use '\n' as a eos token id for both LlaMa and Mistral, but Mistral outputs a '\n' in the first token in most cases in Multi-news while LlaMa does not. Therefore, in most cases Mistral gets a zero score, while LlaMa can get a decent score. After fixing this, the score becomes decent. We would update the arXiv version to fix this, and we kindly refer you to the results shown in this repo to have a preliminary glance of the fixed results.

Thank you again for helping us fixing this issue.

**Comment by yuhuixu1993** [comment]
@Zefan-Cai thanks for your reply. One more question. The running results of visualization.ipynb seems quite different from the paper. Any ideas?
<img width="463" alt="image" src="https://github.com/user-attachments/assets/cf9600d7-80be-4d41-a940-dbfb12c899d4">
