### ISSUE TITLE
What prompt was used in Needle in a Haystack test?

### ISSUE THREAD

**Issue by 66RING** [Zefan-Cai/PyramidKV#4]
I try to reproduce needle test with SnapKV and LWM-Text-Chat-1M mode but the model just refuse to answer. I have tried following prompts in Needle test and the model just generate `</s>`
```
<s>[INST] <<SYS>>
You are a helpful AI bot that answers questions for a user. Keep your response short and direct
<</SYS>>
{ context }

{retrieval_question} Don't give information outside the document or repeat your findings
[/INST]
```
and

```
<s>[INST] <<SYS>>
You are a helpful AI bot that answers questions for a user. Keep your response short and direct
<</SYS>>
{ context }

{retrieval_question} Don't give information outside the document or repeat your findings
[/INST]</s>
```

**Comment by Zefan-Cai** [comment]
Hi, we re-use the prompts provided in https://github.com/FranxYao/Long-Context-Data-Engineering/tree/main/eval/needle.
The prompt is pretty close to your prompt, which is:
[
  {
      "role": "system",
      "content": "You are a helpful AI bot that answers questions for a user. Keep your response short and direct"
  },
  {
      "role": "user",
      "content": context
      },
      {
          "role": "user",
          "content": f"{self.retrieval_question} Don't give information outside the document or repeat your findings. The document definitely contains the answer, and I'm 100% sure. So try your best to find it."
      },
      {
          "role": "assistant",
          "content":"",
      }
]

Have you tried LLaMa-3-8B or Mistral-7B? If your prompt works in these two models, this may not be a prompt issue.

**Comment by Zefan-Cai** [comment]
We will submit our code for Needle in the coming week. We hope that Our implementation of needle can help resolve your issue.

**Comment by Zefan-Cai** [comment]
Hi, we have submitted our code for Needle. We hope that the code could be helpful for your experiments.
Please feel free to contact us if you have any remaining problems.

**Comment by 66RING** [comment]
Looks cool. Thanks you.
