### ISSUE TITLE
correct transformers version

### ISSUE THREAD

**Issue by monster119120** [Zefan-Cai/PyramidKV#7]
The transformers version should be 4.41.1, and in pyramidkv/llama_model.py Line 646, the right code should be
```python
        causal_mask = self._update_causal_mask(
            attention_mask, inputs_embeds, cache_position, past_key_values, output_attentions
        )
```

**Comment by Zefan-Cai** [comment]
Thank you for pointing out! And transformers version 4.40 with not changing of Line 646 can also work.
