### ISSUE TITLE
Llama3-8B model url

### ISSUE THREAD

**Issue by monster119120** [Zefan-Cai/PyramidKV#8]
能麻烦分享一下，论文中用的llama3-8B的链接地址吗？我用huggingface上meta-llama/Meta-Llama-3-8B-Instruct的模型，跑出来的准确率和论文中完全对不上

**Comment by Zefan-Cai** [comment]
我们用的就是meta-llama/Meta-Llama-3-8B-Instruct。不知道能不能分享一下你使用的script、代码以及Transformer、Torch、cuda的版本？我会尝试检查结果对不上的原因。
另外你也可以都跑一下mistral、llama在needle、longBench上的结果，看看是不是所有结果都对不上，方便确定问题。

**Comment by Zefan-Cai** [comment]
Mistral是用的是mistralai/Mistral-7B-Instruct-v0.2

**Comment by monster119120** [comment]
> Mistral是用的是mistralai/Mistral-7B-Instruct-v0.2

mistralai/Mistral-7B-Instruct-v0.2我跑出来时没问题的

**Comment by Zefan-Cai** [comment]
非常感谢您的认可！

我们讨论了一下，如果只有llama3-8B的结果完全对不上，可能是ckpt的原因。不知道是否有可能把meta-llama/Meta-Llama-3-8B误当作meta-llama/Meta-Llama-3-8B-Instruct？

如果还有其他需要帮助的地方或者问题欢迎再与我联系～

**Comment by monster119120** [comment]
> 非常感谢您的认可！
> 
> 我们讨论了一下，如果只有llama3-8B的结果完全对不上，可能是ckpt的原因。不知道是否有可能把meta-llama/Meta-Llama-3-8B误当作meta-llama/Meta-Llama-3-8B-Instruct？
> 
> 如果还有其他需要帮助的地方或者问题欢迎再与我联系～

你们用的是Meta-Llama-3-8B-Instruct-32k吗？

**Comment by Zefan-Cai** [comment]
不是，是8k版本。我们当时进行工作时刚出llama-3-8kk，还没有比较好的32k ckpt。我们的实现是在中间切断，在前面和后面各自保留4k。

**Comment by monster119120** [comment]
感谢作者，已经解决！

**Comment by jameslahm** [comment]
@monster119120 您好，方便问下您是怎么解决的吗？我好像也遇到了Llama3-8B结果不一致的问题，感谢！~
